-- =====================================================================================
-- Rateio -> Omie: seed do mapa unidade -> departamento (GERADO por scripts/rateio/gerar-seed-mapa.mjs)
-- Fonte: mapa_unidade_departamento_RASCUNHO.csv. NÃO editar à mão: regenere o arquivo.
-- BANCO: Supabase FINANCEIRO. Rodar depois de 20261007120000_rateio_omie.sql.
-- 191 vínculos. Duplicatas já consolidadas (ver scripts/rateio/seed-mapa-conflitos.txt).
-- Rodar de novo é seguro: só atualiza linhas com origem = 'csv'; vínculos feitos pela tela
-- (origem = 'tela') nunca são sobrescritos.
-- =====================================================================================

insert into public.rateio_omie_mapa
  (empresa, unidade, unidade_chave, cod_departamento, departamento_nome, confianca, origem, observacao)
values
  ('PRN', 'Alberto Cavalcente', 'ALBERTO CAVALCENTE', 6864062398, 'FHEMIG - ALBERTO CAVALCANTI', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (grafia errada no Bruto)'),
  ('PRN', 'ARARAQUARA (PRN)', 'ARARAQUARA (PRN)', 6864062461, 'SCP ARARAQUARA', 'ALTA', 'csv', null),
  ('PRN', 'ARCO VERDE (PRN)', 'ARCO VERDE (PRN)', 7054706288, 'ARCO VERDE', 'ALTA', 'csv', null),
  ('PRN', 'ARIQUEMES RONDÔNIA (PRN)', 'ARIQUEMES RONDONIA (PRN)', 6864062474, 'ARIQUEMES RONDÔNIA', 'ALTA', 'csv', null),
  ('PRN', 'CACHOEIRINHA (PRN)', 'CACHOEIRINHA (PRN)', 6864062638, 'SCP CACHOEIRINHA', 'ALTA', 'csv', null),
  ('PRN', 'CAXIAS DO SUL - PRN', 'CAXIAS DO SUL - PRN', 7438045531, 'CAXIAS DO SUL', 'ALTA', 'csv', null),
  ('PRN', 'CISRJ (PRN)', 'CISRJ (PRN)', 6864062908, 'CISRJ', 'ALTA', 'csv', null),
  ('PRN', 'CISTEC (PRN)', 'CISTEC (PRN)', 6879190247, 'CISTEC', 'ALTA', 'csv', null),
  ('PRN', 'CUJUBIM (PRN)', 'CUJUBIM (PRN)', 6864062926, 'SCP CUJUBIM', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – ALEGRETE', 'EXERCITO - ALEGRETE', 7247046368, 'EXERCITO ALEGRETE', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - FUSEX SANTIAGO', 'EXERCITO - FUSEX SANTIAGO', 7247256564, 'EXERCITO FUSEX SANTIAGO', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - HGE CURITIBA', 'EXERCITO - HGE CURITIBA', 7247167658, 'EXERCITO HGE CURITIBA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - HGEF', 'EXERCITO - HGEF', 7265570129, 'EXERCITO HGEF', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGEJF', 'EXERCITO - HGEJF', 7297703173, 'EXERCITO - HGEJF', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - HGERJ', 'EXERCITO - HGERJ', 7252160217, 'EXERCITO - HGERJ', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGES', 'EXERCITO - HGES', 7247224741, 'EXERCITO HGES', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGESM', 'EXERCITO - HGESM', 7263753063, 'EXERCITO HGESM', 'ALTA', 'csv', 'ago: Omie +720,00 acima do rateio (ajuste/adicional manual)'),
  ('PRN', 'EXÉRCITO – HGUBA', 'EXERCITO - HGUBA', 7247242160, 'EXERCITO HGUBA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGUFL', 'EXERCITO - HGUFL', 7247247421, 'EXERCITO HGUFL', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - HGUJP', 'EXERCITO - HGUJP', 7426656600, 'Exercito - HGUJP', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGUMBA', 'EXERCITO - HGUMBA', 7247036962, 'EXERCITO HGUMBA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HGUN', 'EXERCITO - HGUN', 7257416430, 'EXERCITO HGUN', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HMAB', 'EXERCITO - HMAB', 7297987000, 'EXERCITOI HMAB', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HMAR', 'EXERCITO - HMAR', 7271810921, 'EXERCITO HMAR', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – HOSPITAL MILITAR DE BELÉM', 'EXERCITO - HOSPITAL MILITAR DE BELEM', 7296230251, 'EXERCITO HOSPITAL GERAL DE BELEM', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - NITEROI', 'EXERCITO - NITEROI', 7264685490, 'EXERCITO - NITEROI', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO  - P M PRAIA VERMELHA', 'EXERCITO - P M PRAIA VERMELHA', 7269346284, 'P M PRAIA VERMELHA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - PM GU CRUZ ALTA', 'EXERCITO - PM GU CRUZ ALTA', 7307206225, 'EXERCITO PMGU CRUZ ALTA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO – PMGU GNA', 'EXERCITO - PMGU GNA', 7257419178, 'EXERCITO PMGU GNA', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO - PMRJ', 'EXERCITO - PMRJ', 7365954836, 'EXERCITO PMRJ', 'ALTA', 'csv', null),
  ('PRN', 'EXÉRCITO HMAPA', 'EXERCITO HMAPA', 7264685660, 'EXERCITO HMAPA', 'ALTA', 'csv', null),
  ('PRN', 'FAEPU - Patos de Minas', 'FAEPU - PATOS DE MINAS', 7297702765, 'FAEPU - Patos de Minas', 'ALTA', 'csv', null),
  ('PRN', 'HINSG – (PRN)', 'HINSG - (PRN)', 7061066584, 'Vitoria SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('PRN', 'HINSG/Anexo HPM – (PRN)', 'HINSG/ANEXO HPM - (PRN)', 7061066584, 'Vitoria SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: dept Vitoria SCP +360,00 acima do rateio (ajuste/adicional manual), so soma jul fecha)'),
  ('PRN', 'HMSB CUIABA (PRN)', 'HMSB CUIABA (PRN)', 7073387702, 'SCP HMSB CUIABA', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL ALBERTO CAVALCANTI - (PRN) - FHEMIG', 'HOSPITAL ALBERTO CAVALCANTI - (PRN) - FHEMIG', 6864062398, 'FHEMIG - ALBERTO CAVALCANTI', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL DE BARBACENA - (PRN) - FHEMIG', 'HOSPITAL DE BARBACENA - (PRN) - FHEMIG', 6864062527, 'FHEMIG - BARBACENA', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL EDUARDO DE MENEZES (PRN) - FHEMIG', 'HOSPITAL EDUARDO DE MENEZES (PRN) - FHEMIG', 6864062957, 'FHEMIG - EDUARDO DE MENEZES', 'ALTA', 'csv', null),
  ('PRN', 'Hospital Infantil João Paulo II (PRN) - FHEMIG', 'HOSPITAL INFANTIL JOAO PAULO II (PRN) - FHEMIG', 7201139947, 'FHEMIG - Infantil João Paulo II', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL JOAO XXIII (PRN) - FHEMIG', 'HOSPITAL JOAO XXIII (PRN) - FHEMIG', 7201139854, 'FHEMIG - João XXIII', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL JULIA KUBITSCHEK (PRN) - FHEMIG', 'HOSPITAL JULIA KUBITSCHEK (PRN) - FHEMIG', 6864063494, 'FHEMIG - Julia Kubitschek', 'ALTA', 'csv', null),
  ('PRN', 'Hospital Maria Amelia Lins (PRN) - FHEMIG', 'HOSPITAL MARIA AMELIA LINS (PRN) - FHEMIG', 7201139623, 'FHEMIG - Maria Amelia Lins', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL METROPOLITANO - PRN', 'HOSPITAL METROPOLITANO - PRN', 7440099123, 'HOSPITAL METROPOLITANO - HMDCC', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: set: unidade nova, o valor 120,45 parece ter caido no dept Porto Velho (ver MGS - PORTO SEGURO), dept HMDCC nao existe na conta Omie de set, sem dept no Omie em set)'),
  ('PRN', 'HOSPITAL REGIONAL DE JOINVILLE (PRN)', 'HOSPITAL REGIONAL DE JOINVILLE (PRN)', 6864063268, 'SCP HOSPITAL REGIONAL DE JOINVILLE', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL REGIONAL JOÃO PENIDO (PRN) - FHEMIG', 'HOSPITAL REGIONAL JOAO PENIDO (PRN) - FHEMIG', 6864063247, 'FHEMIG - JOÃO PENIDO', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL ST ANTONIO - LEBON REGIS (PRN)', 'HOSPITAL ST ANTONIO - LEBON REGIS (PRN)', 6864063546, 'HOSPITAL ST ANTONIO - LEBON REGIS', 'ALTA', 'csv', null),
  ('PRN', 'HOSPITAL UNIVERSITÁRIO DE RIO GRANDE (PRN)', 'HOSPITAL UNIVERSITARIO DE RIO GRANDE (PRN)', 6864064393, 'HOSPITAL UNIVERSITÁRIO DE RIO GRANDE', 'ALTA', 'csv', null),
  ('PRN', 'IBIRAMA (PRN)', 'IBIRAMA (PRN)', 6875302204, 'IBIRAMA', 'ALTA', 'csv', null),
  ('PRN', 'IMADI - PRN', 'IMADI - PRN', 7427032713, 'IMADI', 'ALTA', 'csv', null),
  ('PRN', 'JANDAIA (PRN)', 'JANDAIA (PRN)', 7392683755, 'JANDAIA', 'ALTA', 'csv', null),
  ('PRN', 'JUCELINO KUBISTCKET', 'JUCELINO KUBISTCKET', 6864063494, 'FHEMIG - Julia Kubitschek', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: unidade com nome digitado errado (569,34 = 169,34+400), nao lancada no Omie de set, destino presumido pelo nome)'),
  ('PRN', 'LARANJAL DO JARI (PRN)', 'LARANJAL DO JARI (PRN)', 6864063533, 'LARANJAL DO JARI', 'ALTA', 'csv', null),
  ('PRN', 'MADRE DE DIO (PRN)', 'MADRE DE DIO (PRN)', 7127371637, 'MADRE DE DIO', 'ALTA', 'csv', null),
  ('PRN', 'MARABA (PRN)', 'MARABA (PRN)', 6864063573, 'MARABA', 'ALTA', 'csv', null),
  ('PRN', 'MGS - HOSPITAL TEIXEIRA DE FREITAS (PRN)', 'MGS - HOSPITAL TEIXEIRA DE FREITAS (PRN)', 6864064144, 'HOSPITAL TEIXEIRA DE FREITAS', 'ALTA', 'csv', null),
  ('PRN', 'MGS - PAULO AFONSO (PRN)', 'MGS - PAULO AFONSO (PRN)', 7445319907, 'MGS - Paulo Afonso', 'ALTA', 'csv', 'jul: diff 1,15 (Omie 121,32 x rateio 122,47) = diferenca total do mes'),
  ('PRN', 'MHC - SALVADOR', 'MHC - SALVADOR', 7421803397, 'MGS - SALVADOR', 'ALTA', 'csv', null),
  ('PRN', 'MORRETES PRN', 'MORRETES PRN', 7415312750, 'MORRETES', 'ALTA', 'csv', null),
  ('PRN', 'PAM BOA ESPERANÇA (PRN)', 'PAM BOA ESPERANCA (PRN)', 6987234184, 'PAM BOA ESPERANÇA', 'ALTA', 'csv', null),
  ('PRN', 'PASSO FUNDO (PRN)', 'PASSO FUNDO (PRN)', 6864063761, 'PASSO FUNDO', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN', 'POLICLINICA DE GUANAMBI (PRN)', 'POLICLINICA DE GUANAMBI (PRN)', 6864063015, 'POLICLINICA DE GUANAMBI', 'ALTA', 'csv', null),
  ('PRN', 'POLICLINICA JACOBINA (PRN)', 'POLICLINICA JACOBINA (PRN)', 6864063237, 'POLICLINICA JACOBINA', 'ALTA', 'csv', null),
  ('PRN', 'POLICLINICA VALENÇA (PRN)', 'POLICLINICA VALENCA (PRN)', 6864064216, 'POLICLINICA VALENÇA', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - CENTRO DE ESPECIALIDADES MÉDICAS', 'PORTO VELHO - CENTRO DE ESPECIALIDADES MEDICAS', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - CENTRO ESPECIALIZADO RAFAEL VAZ E SILVA', 'PORTO VELHO - CENTRO ESPECIALIZADO RAFAEL VAZ E SILVA', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - MATERNIDADE', 'PORTO VELHO - MATERNIDADE', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - PRONTO ATENDIMENTO ANA ADELAIDE', 'PORTO VELHO - PRONTO ATENDIMENTO ANA ADELAIDE', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - PRONTO ATENDIMENTO JOSÉ ADELINO', 'PORTO VELHO - PRONTO ATENDIMENTO JOSE ADELINO', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - UPA JACI PARANÁ', 'PORTO VELHO - UPA JACI PARANA', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - UPA LESTE', 'PORTO VELHO - UPA LESTE', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PORTO VELHO - UPA SUL', 'PORTO VELHO - UPA SUL', 7055238988, 'Porto Velho', 'ALTA', 'csv', null),
  ('PRN', 'PRN Mambucaba (PRN)', 'PRN MAMBUCABA (PRN)', 6881740809, 'Angra dos Reis SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: Angra dos Reis, soma fecha em jul e ago)'),
  ('PRN', 'PRN MEDCENTER AÇAILÂNDIA', 'PRN MEDCENTER ACAILANDIA', 7392680171, 'MEDCENTER', 'ALTA', 'csv', null),
  ('PRN', 'RIO DO SUL (PRN)', 'RIO DO SUL (PRN)', 6864063891, 'RIO DO SUL', 'ALTA', 'csv', null),
  ('PRN', 'RIO GRANDE (PRN)', 'RIO GRANDE (PRN)', 6864063910, 'SCP RIO GRANDE', 'ALTA', 'csv', null),
  ('PRN', 'SANTANA DE BOA VISTA (PRN)', 'SANTANA DE BOA VISTA (PRN)', 6864064019, 'SANTANA DE BOA VISTA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN', 'SANTAREM - (PRN)', 'SANTAREM - (PRN)', 6948281213, 'SANTAREM', 'ALTA', 'csv', null),
  ('PRN', 'SÃO MIGUEL DO OESTE (PRN)', 'SAO MIGUEL DO OESTE (PRN)', 6948281294, 'SÃO MIGUEL DO OESTE', 'ALTA', 'csv', null),
  ('PRN', 'UPA ABRAÃO', 'UPA ABRAAO', 6881740809, 'Angra dos Reis SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('PRN', 'UPA FRADE', 'UPA FRADE', 6881740809, 'Angra dos Reis SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('PRN', 'UPA PRAIA GRANDE (PRN)', 'UPA PRAIA GRANDE (PRN)', 6864063807, 'SCP UPA PRAIA GRANDE', 'ALTA', 'csv', null),
  ('PRN', 'UPA SOROCABA - (PRN)', 'UPA SOROCABA - (PRN)', 6864064108, 'SCP UPA SOROCABA', 'ALTA', 'csv', null),
  ('PRN', 'VITORINO FREIRE (PRN)', 'VITORINO FREIRE (PRN)', 6886853134, 'SCP VITORINO FREIRE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'APICE TELE - HOSPITAL METROPOLITANO', 'APICE TELE - HOSPITAL METROPOLITANO', 7440099123, 'HOSPITAL METROPOLITANO - HMDCC', 'ALTA', 'csv', null),
  ('PRN_APICE', 'ARARAQUARA - APICE TELE', 'ARARAQUARA - APICE TELE', 6864062461, 'SCP ARARAQUARA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: diff +1,05 (rateio x Omie), nome bate e soma quase fecha (dif min R$ 1.05))'),
  ('PRN_APICE', 'ARIQUEMES - APICE TELE', 'ARIQUEMES - APICE TELE', 6864062474, 'ARIQUEMES RONDÔNIA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'CAXIAS DO SUL PRN- APICE TELE', 'CAXIAS DO SUL PRN- APICE TELE', 7438045531, 'CAXIAS DO SUL', 'ALTA', 'csv', null),
  ('PRN_APICE', 'CISRJ - APICE TELE', 'CISRJ - APICE TELE', 6864062908, 'CISRJ', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'CISVITA POLICLÍNICA  APICE TELE', 'CISVITA POLICLINICA APICE TELE', 6864063836, 'POLICLINICA CISVITA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0 nos meses, so nome)'),
  ('PRN_APICE', 'CUJUBIM - APICE TELE', 'CUJUBIM - APICE TELE', 6864062926, 'SCP CUJUBIM', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0/0,31, so nome, nome bate e soma quase fecha (dif min R$ 0.03))'),
  ('PRN_APICE', 'EXÉRCITO – ALEGRETE - APICE TELE', 'EXERCITO - ALEGRETE - APICE TELE', 7247046368, 'EXERCITO ALEGRETE', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO - HGEF - APICE TELE', 'EXERCITO - HGEF - APICE TELE', 7265570129, 'EXERCITO HGEF', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO - HGEJF APICE TELE', 'EXERCITO - HGEJF APICE TELE', 7297703173, 'EXERCITO - HGEJF', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO - HGERJ -APICE TELE', 'EXERCITO - HGERJ -APICE TELE', 7252160217, 'EXERCITO - HGERJ', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO – HGESM - APICE TELE', 'EXERCITO - HGESM - APICE TELE', 7263753063, 'EXERCITO HGESM', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO – HGUBA - APICE TELE', 'EXERCITO - HGUBA - APICE TELE', 7247242160, 'EXERCITO HGUBA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO – HGUFL  APICE TELE', 'EXERCITO - HGUFL APICE TELE', 7247247421, 'EXERCITO HGUFL', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO - HGUJP - APICE TELE', 'EXERCITO - HGUJP - APICE TELE', 7426656600, 'Exercito - HGUJP', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO - HGUMBA - APICE TELE', 'EXERCITO - HGUMBA - APICE TELE', 7247036962, 'EXERCITO HGUMBA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO - HGUN - APICE TELE', 'EXERCITO - HGUN - APICE TELE', 7257416430, 'EXERCITO HGUN', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: diff +0,31, sem dept no Omie em set, nome bate e soma quase fecha (dif min R$ 0.31))'),
  ('PRN_APICE', 'EXERCITO - HMAB -APICE TELE', 'EXERCITO - HMAB -APICE TELE', 7297987000, 'EXERCITOI HMAB', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO – HOSPITAL MILITAR DE BELÉM - APICE TELE', 'EXERCITO - HOSPITAL MILITAR DE BELEM - APICE TELE', 7296230251, 'EXERCITO HOSPITAL GERAL DE BELEM', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO  - P M PRAIA VERMELHA -APICE TELE', 'EXERCITO - P M PRAIA VERMELHA -APICE TELE', 7269346284, 'P M PRAIA VERMELHA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO - PM GU CRUZ ALTA - APICE TELE', 'EXERCITO - PM GU CRUZ ALTA - APICE TELE', 7307206225, 'EXERCITO PMGU CRUZ ALTA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, so nome)'),
  ('PRN_APICE', 'EXÉRCITO FUSEX SANTIAGO - APICE TELE', 'EXERCITO FUSEX SANTIAGO - APICE TELE', 7247256564, 'EXERCITO FUSEX SANTIAGO', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO HGE CURITIBA- APICE', 'EXERCITO HGE CURITIBA- APICE', 7247167658, 'EXERCITO HGE CURITIBA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO HGES - APICE TELE', 'EXERCITO HGES - APICE TELE', 7247224741, 'EXERCITO HGES', 'ALTA', 'csv', null),
  ('PRN_APICE', 'EXÉRCITO HMAPA - APICE TELE', 'EXERCITO HMAPA - APICE TELE', 7264685660, 'EXERCITO HMAPA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO HMAR - APICE TELE', 'EXERCITO HMAR - APICE TELE', 7271810921, 'EXERCITO HMAR', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'EXÉRCITO- PMGU GNA - APICE TELE', 'EXERCITO- PMGU GNA - APICE TELE', 7257419178, 'EXERCITO PMGU GNA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'FAEPU - Patos de Minas - APICE TELE', 'FAEPU - PATOS DE MINAS - APICE TELE', 7297702765, 'FAEPU - Patos de Minas', 'ALTA', 'csv', null),
  ('PRN_APICE', 'HINSG – ÁPICE TELE', 'HINSG - APICE TELE', 7061066584, 'Vitoria SCP', 'ALTA', 'csv', 'mesma unidade de HINSG (PRN), confirmada pelo financeiro em 2026-10-07'),
  ('PRN_APICE', 'HINSG/Anexo HPM – ÁPICE TELE', 'HINSG/ANEXO HPM - APICE TELE', 7061066584, 'Vitoria SCP', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('PRN_APICE', 'HMSB CUIABÁ - APICE TELE', 'HMSB CUIABA - APICE TELE', 7073387702, 'SCP HMSB CUIABA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'HOSP. REGIONAL DE JOINVILLE  - APICE TELE', 'HOSP. REGIONAL DE JOINVILLE - APICE TELE', 6864063268, 'SCP HOSPITAL REGIONAL DE JOINVILLE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'HOSPITAL ALBERTO CAVALCANTI - APICE TELE - FHEMIG', 'HOSPITAL ALBERTO CAVALCANTI - APICE TELE - FHEMIG', 6864062398, 'FHEMIG - ALBERTO CAVALCANTI', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'HOSPITAL DE BARBACENA FEMIG - APICE TELE - FHEMIG', 'HOSPITAL DE BARBACENA FEMIG - APICE TELE - FHEMIG', 6864062527, 'FHEMIG - BARBACENA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'HOSPITAL EDUARDO DE MENEZES - APICE TELE - FHEMIG', 'HOSPITAL EDUARDO DE MENEZES - APICE TELE - FHEMIG', 6864062957, 'FHEMIG - EDUARDO DE MENEZES', 'ALTA', 'csv', null),
  ('PRN_APICE', 'Hospital Infantil João Paulo II - APICE TELE - FHEMIG', 'HOSPITAL INFANTIL JOAO PAULO II - APICE TELE - FHEMIG', 7201139947, 'FHEMIG - Infantil João Paulo II', 'ALTA', 'csv', null),
  ('PRN_APICE', 'Hospital Julia Kubitschek - APICE TELE - FHEMIG', 'HOSPITAL JULIA KUBITSCHEK - APICE TELE - FHEMIG', 6864063494, 'FHEMIG - Julia Kubitschek', 'ALTA', 'csv', null),
  ('PRN_APICE', 'HOSPITAL MUNICIPAL DE ITAPIRA - APICE TELE', 'HOSPITAL MUNICIPAL DE ITAPIRA - APICE TELE', 6864064855, 'Itapira', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, departamento Itapira esta INATIVO no Omie)'),
  ('PRN_APICE', 'HOSPITAL REGIONAL JOÃO PENIDO - APICE TELE - FHEMIG', 'HOSPITAL REGIONAL JOAO PENIDO - APICE TELE - FHEMIG', 6864063247, 'FHEMIG - JOÃO PENIDO', 'ALTA', 'csv', null),
  ('PRN_APICE', 'Hospital Universitário de Rio Grande - Apice Tele', 'HOSPITAL UNIVERSITARIO DE RIO GRANDE - APICE TELE', 6864064393, 'HOSPITAL UNIVERSITÁRIO DE RIO GRANDE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'IBIRAMA - APICE TELE', 'IBIRAMA - APICE TELE', 6875302204, 'IBIRAMA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'IMADI - PRN APICE TELE', 'IMADI - PRN APICE TELE', 7427032713, 'IMADI', 'ALTA', 'csv', null),
  ('PRN_APICE', 'JANDAIA (PRN) - APICE TELE', 'JANDAIA (PRN) - APICE TELE', 7392683755, 'JANDAIA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07: Jandaia fica so no departamento JANDAIA do Omie PRN'),
  ('PRN_APICE', 'MARABA APICE TELE', 'MARABA APICE TELE', 6864063573, 'MARABA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: Omie 157,08 x rateio 209,44 (-52,36))'),
  ('PRN_APICE', 'MEDIMAGEM PALHOÇA - APICE TELE', 'MEDIMAGEM PALHOCA - APICE TELE', 6879190206, 'MEDIMAGEM PALHOÇA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'MGS - HOSPITAL TEIXEIRA DE FREITAS APICE TELE', 'MGS - HOSPITAL TEIXEIRA DE FREITAS APICE TELE', 6864064144, 'HOSPITAL TEIXEIRA DE FREITAS', 'ALTA', 'csv', null),
  ('PRN_APICE', 'MGS - PAULO AFONSO (PRN) - APICE TELE', 'MGS - PAULO AFONSO (PRN) - APICE TELE', 7445319907, 'MGS - Paulo Afonso', 'ALTA', 'csv', null),
  ('PRN_APICE', 'MHC - SALVADOR - APICE TELE', 'MHC - SALVADOR - APICE TELE', 7421803397, 'MGS - SALVADOR', 'ALTA', 'csv', null),
  ('PRN_APICE', 'MORRETES PRN - APICE TELE', 'MORRETES PRN - APICE TELE', 7415312750, 'MORRETES', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PAM BOA ESPERANÇA - (APICE TELE)', 'PAM BOA ESPERANCA - (APICE TELE)', 6987234184, 'PAM BOA ESPERANÇA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PASSO FUNDO - APICE TELE', 'PASSO FUNDO - APICE TELE', 6864063761, 'PASSO FUNDO', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'PRN - LARANJAL DO JARI - APICE TELE', 'PRN - LARANJAL DO JARI - APICE TELE', 6864063533, 'LARANJAL DO JARI', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PRN ARCO VERDE - APICE TELE', 'PRN ARCO VERDE - APICE TELE', 7054706288, 'ARCO VERDE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PRN CISTEC - APICE TELE', 'PRN CISTEC - APICE TELE', 6879190247, 'CISTEC', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'PRN HOSPITAL JOAO XXIII APICE TELE - FHEMIG', 'PRN HOSPITAL JOAO XXIII APICE TELE - FHEMIG', 7201139854, 'FHEMIG - João XXIII', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PRN Hospital Maria Amelia Lins - APICE TELE - FHEMIG', 'PRN HOSPITAL MARIA AMELIA LINS - APICE TELE - FHEMIG', 7201139623, 'FHEMIG - Maria Amelia Lins', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: 52,36 nao lancado no Omie, sem dept no Omie em ago,set, nome bate e soma quase fecha (dif min R$ 1.57))'),
  ('PRN_APICE', 'PRN HOSPITAL SANTO ANTONIO - APICE TELE', 'PRN HOSPITAL SANTO ANTONIO - APICE TELE', 6864063546, 'HOSPITAL ST ANTONIO - LEBON REGIS', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PRN JACOBINA - APICE TELE', 'PRN JACOBINA - APICE TELE', 6864063237, 'POLICLINICA JACOBINA', 'ALTA', 'csv', null),
  ('PRN_APICE', 'PRN POLICLINICA BAIXO SUL -VALENÇA BAHIA - APICE TELE', 'PRN POLICLINICA BAIXO SUL -VALENCA BAHIA - APICE TELE', 6864064216, 'POLICLINICA VALENÇA', 'ALTA', 'csv', 'sem dept no Omie em set'),
  ('PRN_APICE', 'RIO DO SUL - APICE TELE', 'RIO DO SUL - APICE TELE', 6864063891, 'RIO DO SUL', 'ALTA', 'csv', null),
  ('PRN_APICE', 'RIO GRANDE - APICE TELE', 'RIO GRANDE - APICE TELE', 6864063910, 'SCP RIO GRANDE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'SANTARÉM - APICE TELE', 'SANTAREM - APICE TELE', 6948281213, 'SANTAREM', 'ALTA', 'csv', null),
  ('PRN_APICE', 'SÃO MIGUEL DO OESTE - APICE TELE', 'SAO MIGUEL DO OESTE - APICE TELE', 6948281294, 'SÃO MIGUEL DO OESTE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'UPA PRAIA GRANDE - APICE TELE', 'UPA PRAIA GRANDE - APICE TELE', 6864063807, 'SCP UPA PRAIA GRANDE', 'ALTA', 'csv', null),
  ('PRN_APICE', 'UPA SAPIRANGA - APICE TELE', 'UPA SAPIRANGA - APICE TELE', 6864064044, 'SCP UPA SAPIRANGA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, so nome)'),
  ('PRN_APICE', 'Upa Sorocaba - Apice Tele', 'UPA SOROCABA - APICE TELE', 6864064108, 'SCP UPA SOROCABA', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, so nome)'),
  ('PRN_APICE', 'VITORINO FREIRE - APICE TELE', 'VITORINO FREIRE - APICE TELE', 6886853134, 'SCP VITORINO FREIRE', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'ALFREDO WAGNER', 'ALFREDO WAGNER', 2435942639, 'Alfredo Wagner', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'CANELINHA', 'CANELINHA', 2462820077, 'Canelinha', 'ALTA', 'csv', 'dept Canelinha ausente do Omie em ago/set (52,36 nao lancado ou diluido em Palmeiras/Frutal), sem dept no Omie em ago,set'),
  ('MEDIMAGEM', 'GUARATA DO NORTE', 'GUARATA DO NORTE', 2435944137, 'Guaranta do Norte', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'LAGOA FORMOSA', 'LAGOA FORMOSA', 2883563212, 'Lagoa Formosa', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM - SÃO JOÃO DEL REY', 'MEDIMAGEM - SAO JOAO DEL REY', 2593493101, 'SCP SAO JOAO DEL REI', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM ABDON BATISTA - SC', 'MEDIMAGEM ABDON BATISTA - SC', 2601612022, 'Abdon Batista', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM BOM SUCESSO', 'MEDIMAGEM BOM SUCESSO', 2608684069, 'SCP BOM SUCESSO', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM CEM - PALMEIRAS DE GOIAS', 'MEDIMAGEM CEM - PALMEIRAS DE GOIAS', 2791818564, 'PALMEIRAS DE GOIAS', 'ALTA', 'csv', 'jul: Omie 2045,70 = HNAM+CEM+Nova Mutum(52,67), ago/set Omie tem diferencas (+57,34 / +103,82) por unidades sem dept'),
  ('MEDIMAGEM', 'MEDIMAGEM ESTÂNCIA VELHA', 'MEDIMAGEM ESTANCIA VELHA', 2601601020, 'Estância Velha', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM FRUTAL', 'MEDIMAGEM FRUTAL', 2883563390, 'Frutal', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM HNAM - PALMEIRAS DE GOIAS', 'MEDIMAGEM HNAM - PALMEIRAS DE GOIAS', 2791818564, 'PALMEIRAS DE GOIAS', 'ALTA', 'csv', 'jul: Omie 2045,70 = HNAM+CEM+Nova Mutum(52,67), ago/set Omie tem diferencas (+57,34 / +103,82) por unidades sem dept'),
  ('MEDIMAGEM', 'MEDIMAGEM IBIRAMA', 'MEDIMAGEM IBIRAMA', 2834946312, 'Medimagem Ibirama', 'ALTA', 'csv', 'set: 52,36 sem dept, jul/ago ok, sem dept no Omie em set'),
  ('MEDIMAGEM', 'MEDIMAGEM IPATINGA', 'MEDIMAGEM IPATINGA', 2562002386, 'SCP IPATINGA', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM IPIRANGA', 'MEDIMAGEM IPIRANGA', 2435944177, 'Ipiranga', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM MATINHOS', 'MEDIMAGEM MATINHOS', 2722592715, 'Matinhos', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM NOVA MUTUM', 'MEDIMAGEM NOVA MUTUM', 2792577854, 'NOVA MUTUM', 'ALTA', 'csv', 'jul: valor 52,67 caiu em PALMEIRAS DE GOIAS (dept Nova Mutum so existe a partir de ago), sem dept no Omie em jul'),
  ('MEDIMAGEM', 'MEDIMAGEM ORTIGUEIRA', 'MEDIMAGEM ORTIGUEIRA', 2833096912, 'ORTIGUEIRA', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM PINDAMONHANGABA', 'MEDIMAGEM PINDAMONHANGABA', 2615393233, 'Pindamonhangaba', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM POÁ', 'MEDIMAGEM POA', 2665295114, 'Poá', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM SÃO JOÃO EVANGELISTA', 'MEDIMAGEM SAO JOAO EVANGELISTA', 2722872993, 'São João Evangelista', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM SÃO MATEUS', 'MEDIMAGEM SAO MATEUS', 2659458416, 'São Mateus', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'MEDIMAGEM SÃO PEDRO', 'MEDIMAGEM SAO PEDRO', 2435942730, 'Vitoria', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('MEDIMAGEM', 'MEDIMAGEM SESI', 'MEDIMAGEM SESI', 2631959942, 'SESI', 'ALTA', 'csv', 'dept SESI so aparece em jul, sem dept no Omie em ago,set'),
  ('MEDIMAGEM', 'MEDIMAGEM UNAÍ', 'MEDIMAGEM UNAI', 2883563294, 'Unai', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'NOVA TRENTO', 'NOVA TRENTO', 2435942488, 'Nova Trento', 'ALTA', 'csv', null),
  ('MEDIMAGEM', 'SESI MS 1', 'SESI MS 1', 2869644242, 'SESI MS 1', 'ALTA', 'csv', 'dept SESI MS 1 so aparece em jul/ago, sem dept no Omie em set'),
  ('MEDIMAGEM', 'UPA SUA', 'UPA SUA', 2435942730, 'Vitoria', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07'),
  ('MEDIMAGEM_APICE', 'APICE TELE - MEDIMAGEM HNAM - PALMEIRAS DE GOIAS', 'APICE TELE - MEDIMAGEM HNAM - PALMEIRAS DE GOIAS', 2791818564, 'PALMEIRAS DE GOIAS', 'ALTA', 'csv', 'jul: Omie nao tem dept Palmeiras na conta Apice, 52,36 caiu em MEDIMAGEM DIAGNOSTICOS ou SJ Evangelista (ambiguo), sem dept no Omie em jul'),
  ('MEDIMAGEM_APICE', 'APICE TELE - MEDIMAGEM SÃO JOÃO EVANGELISTA', 'APICE TELE - MEDIMAGEM SAO JOAO EVANGELISTA', 2722872993, 'São João Evangelista', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'APICE TELE MEDIMAGEM SÃO MATEUS', 'APICE TELE MEDIMAGEM SAO MATEUS', 2659458416, 'São Mateus', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM - SAO JOAO DEL REY - APICE TELE', 'MEDIMAGEM - SAO JOAO DEL REY - APICE TELE', 2593493101, 'SCP SAO JOAO DEL REI', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM ESTÂNCIA VELHA - APICE TELE', 'MEDIMAGEM ESTANCIA VELHA - APICE TELE', 2601601020, 'Estância Velha', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM IBIRAMA  APICE TELE', 'MEDIMAGEM IBIRAMA APICE TELE', 2834946312, 'Medimagem Ibirama', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, so nome)'),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM IPATINGA - APICE TELE', 'MEDIMAGEM IPATINGA - APICE TELE', 2562002386, 'SCP IPATINGA', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM IPIRANGA - APICE TELE', 'MEDIMAGEM IPIRANGA - APICE TELE', 2435944177, 'Ipiranga', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: valor 0, so nome)'),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM MATINHOS APICE TELE', 'MEDIMAGEM MATINHOS APICE TELE', 2722592715, 'Matinhos', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM NOVA MUTUM APICE TELE', 'MEDIMAGEM NOVA MUTUM APICE TELE', 2792577854, 'NOVA MUTUM', 'ALTA', 'csv', 'jul: 52,36 caiu em SJ Evangelista (ambiguo), ago ok, sem dept no Omie em jul'),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM ORTIGUEIRA APICE TELE', 'MEDIMAGEM ORTIGUEIRA APICE TELE', 2833096912, 'ORTIGUEIRA', 'ALTA', 'csv', null),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM UNAÍ APICE TELE', 'MEDIMAGEM UNAI APICE TELE', 2883563294, 'Unai', 'ALTA', 'csv', 'confirmado pelo financeiro em 2026-10-07 (antes: ago: Omie 70,21 x rateio 62,86 (+7,35))'),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM UPA SÃO PEDRO - APICE TELE', 'MEDIMAGEM UPA SAO PEDRO - APICE TELE', 2435942730, 'Vitoria', 'ALTA', 'csv', 'mesma unidade de MEDIMAGEM SÃO PEDRO, confirmada pelo financeiro em 2026-10-07'),
  ('MEDIMAGEM_APICE', 'MEDIMAGEM Upa Sua - Apice Tele', 'MEDIMAGEM UPA SUA - APICE TELE', 2435942730, 'Vitoria', 'ALTA', 'csv', 'mesma unidade de UPA SUA, confirmada pelo financeiro em 2026-10-07')
on conflict (empresa, unidade_chave) do update set
  unidade           = excluded.unidade,
  cod_departamento  = excluded.cod_departamento,
  departamento_nome = excluded.departamento_nome,
  confianca         = excluded.confianca,
  observacao        = excluded.observacao,
  atualizado_em     = now()
where public.rateio_omie_mapa.origem = 'csv';
