-- ⛔ NÃO APLIQUE ESTE ARQUIVO. Ele foi neutralizado de propósito.
--
-- O conteúdo original (um `CREATE OR REPLACE FUNCTION public.send_whatsapp_message`
-- com 12 argumentos, trazendo o corpo inteiro da função do repositório) foi
-- removido daqui porque aplicá-lo **derrubaria o envio de mensagens da empresa**.
-- Substituído por `20260820180000_sem_assinatura_a_partir_de_producao.sql`.
--
-- Dois motivos, e o segundo é o grave:
--
-- 1. DRIFT DE MIGRATIONS
--    O corpo aqui vinha do repositório, e neste projeto o que está versionado
--    NÃO corresponde ao que roda em produção. Medido em 20/08/2026: a definição
--    em produção tinha 12.220 caracteres e este arquivo 12.672 — o parâmetro e o
--    comentário novos explicavam só ~270 dessa diferença. Aplicar substituiria o
--    corpo vivo por uma cópia possivelmente desatualizada, revertendo em silêncio
--    qualquer correção feita fora do controle de migrations.
--
-- 2. AMBIGUIDADE — QUEBRARIA TODO O ENVIO
--    Em PostgreSQL, a lista de argumentos faz parte da IDENTIDADE da função.
--    A função em produção tem 11 argumentos; este arquivo criava uma de 12 e não
--    removia a antiga. `CREATE OR REPLACE` com lista de argumentos diferente NÃO
--    substitui: cria uma SEGUNDA função. Com as duas coexistindo, toda chamada de
--    11 argumentos — ou seja, todo envio normal do app — casa com ambas, e o
--    Postgres recusa com "function ... is not unique".
--
--    O estrago seria muito pior que o problema original: em vez de o toggle
--    "sem assinatura" falhar, NENHUMA mensagem sairia.
--
-- Como foi resolvido: a migration substituta lê a definição REAL de produção
-- dentro do próprio banco, aplica só as duas alterações necessárias (o parâmetro
-- e a condição da assinatura), REMOVE a versão de 11 argumentos antes de criar a
-- de 12, e restaura os GRANTs que o DROP apaga. Nada do corpo trafega para fora.
--
-- Aplicada em produção em 20/08/2026. Verificado depois: 1 função (não 2), com 12
-- argumentos, e os dois caminhos de chamada — o de 11 e o de 12 — resolvendo sem
-- ambiguidade.
--
-- Lição para a próxima vez: acrescentar parâmetro a uma função existente exige
-- DROP explícito da assinatura antiga. Nunca só `CREATE OR REPLACE`.

SELECT 'Arquivo neutralizado. Ver 20260820180000_sem_assinatura_a_partir_de_producao.sql' AS aviso;
